import Head from 'next/head';
import { Sidebar } from '../layout';
export default function Home() {
  return (
    <div className=''>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-red-300 max-w-[1375px] mx-auto min-h-screen'>
        <Sidebar />
        
      </main>
    </div>
  )
}
