import Head from 'next/head';
import { Sidebar, Content, Aside, Container } from '../layout';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Sidebar />
        <Content />
        <Aside />
      </Container>
    </div>
  )
}
