import Head from 'next/head';
import { TextBox } from '../components';
import { PopularIcon } from '../layout/icons';


export default function Profile() {
    return (
      <>
        <Head>
          <title>Profile | Twitter</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <header className='sticky top-0 bg-white z-10 flex justify-between p-6 items-center border-b'>
          <span>
            <b>PROFILE</b>
          </span>
          <span>
            <PopularIcon className={"w-7 h-7"} />
          </span>
        </header>
        profil
      </>
    )
  }
  